### ISSUE TITLE
READMEがあるといいかも

### ISSUE THREAD

**Issue by kaminchu** [BitzenyCoreDevelopers/portal.bitzeny.info#2]
外野からすみません。
BitZenyフォーラムからこちらを見つけたので投稿しました。

README.mdを簡単でいいので置いていただけると、githubから入ってきた方の目にも止まりやすいかなぁと思いました。
「bitzeny」で検索した際に、この投稿時点ではこのプロジェクトが一番スター数ありましたし、github経由ではこのプロジェクトが一番目につくのかなぁと思ったので。

ご検討のほどよろしくお願いします。

**Comment by yossi1114net** [comment]
I understand. I will create it as soon as possible.
Thanks!

**Comment by yossi1114net** [comment]
I created it. We probably change README.md.

**Comment by hitobb** [comment]
In order to add Readme.md, I recreated the development branch.

When editing the readme, please use Dev Branch instead of master.
I'm afraid that the readme.md will not be updated when a new site is completed.

Thanks.

**Comment by kaminchu** [comment]
Thank you for your support.

I'm sure I'v created it, so I'll close this issue.
